### ISSUE TITLE
Early Adopters!

### ISSUE THREAD

**Issue by dhirschfeld** [channel-mirrors/conda_oci_mirror#10]
So, I'm pretty excited about this! :rocket:

It sounds like `micormamba` can't yet install from an OCI registry (e.g. GitHub Packages):
> *Unfortunately mamba's direct-to-OCI communication is still waiting for powerloader to be fully integrated :)*

...but that there may be code somewhere that can *publish* to GitHub Packages?
> *The mirror is already complete and updates every 6 hours :)*
> *And mamba is pretty close to being able to talk directly to it!*

I'm already using `micromamba` and `boa` in my CI and would love to start making use of this functionality as soon as possible!

Even if it's not fully stable yet, and there's no way (yet) to install from an OCI registry, I'd like to start integrating *publishing* to GitHub Packages into my CI and would be happy to give feedback along the way.

If you're interested in having early adopters kick the tyres, just let me know how I can publish a package to GitHub Packages after my `boa build` step!

**Comment by wolfv** [comment]
Awesome! 

Yes, so far we do not have a `boa push` or `micromamba push` :) But maybe that'll come -- as you discovered, the `powerloader` network backend also supports uploading, and we plan to integrate powerloader asap in mamba.

What this package here (`conda_oci_mirror`) does, is to upload a given package to OCI registries (or clone many packages based on a given repodata.json).

It is pure python and has a simple OCI implementation based on requests. We upload 3 files per conda package:

- index.json as `application/vnd.conda.info.index.v1+json`
- info.tar.gz as `application/vnd.conda.info.v1.tar+gzip`
- package .tar.bz2 / .conda as `application/vnd.conda.package.v1` or `application/vnd.conda.package.v2`

We have this function https://github.com/channel-mirrors/conda_oci_mirror/blob/e07c4371b029497acd9c8db298fb8c5b9f7d2058/conda_oci_mirror/oci_mirror.py#L89 to upload an individual package. For that you'd need to create an OCI object (very simple, host is `ghcr.io` and you need a token). I don't think we've exposed that function yet to the CLI, but that shoudl be quite straightforward.

The other option would be to use `oras` or `oras-py` to upload your package. However, that wouldn't automatically create the additional layers with the `index.json` and `info.tar.gz`.
The benefit of these two additional layers is that they can be individually retrieved (all files are actually addressed by SHA256 sum), which will open up some interesting use cases in the future I hope :)

**Comment by dhirschfeld** [comment]
It sounds like `upload_conda_package` is the way to go. My timeline for seriously testing this out is probably *"sometime this year"* but I'll be sure to post back here any progress... or problems! 😀 🙏

**Comment by dhirschfeld** [comment]
Since there's nothing to action here I'll go ahead and close this issue.

I'm trying out `powerloader` (https://github.com/mamba-org/powerloader/issues/135#issuecomment-1357740727) but will keep an eye out here as well...
